apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: Dokument Hendelser
    dcat.data.nav.no/description: Intern kø av hendelser som beskriver status på bidrag dokumenter
  name: dokument
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: bidrag
      application: bidrag-dokument-journalpost
      access: readwrite
    - team: bidrag
      application: bidrag-dokument-bestilling
      access: readwrite
    - team: bidrag
      application: bidrag-dokument-forsendelse
      access: readwrite
    - team: bidrag
      application: bidrag-cli
      access: read
    - team: bidrag
      application: bisys
      access: readwrite
    - team: bidrag
      application: bidrag-kafka-manager
      access: read