apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: journalpost
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: dev-gcp
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: bidrag
      application: bidrag-dokument-journalpost
      access: readwrite
    - team: bidrag
      application: bidrag-dokument-testdata
      access: read
