apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: {{ journalpost-name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: {{ kafka-pool }}
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
  {{#each acl}}
    - team: bidrag
      application: {{@key}}
      access: "{{this}}"
  {{/each}}
