apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: Sak Hendelser Q*
    dcat.data.nav.no/description: Intern kø av hendelser som inneholder detaljer på en bidrag sak
  name: sak-feature
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: bidrag
      application: bidrag-cli
      access: readwrite
    - team: bidrag
      application: bidrag-kafka-manager
      access: read
    - team: bidrag
      application: bisys
      access: readwrite
    - team: bidrag
      application: bidrag-sak-feature
      access: readwrite
    - team: bidrag
      application: bidrag-sak-q1
      access: readwrite
    - team: bidrag
      application: bidrag-bidragskalkulator-api
      access: read
