apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: Vedtakshendelser statistikk
    dcat.data.nav.no/description: Intern kø av vedtakshendelser omformet og tilpasset behovet for statistikk, team bidrag
  name: statistikk
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: bidrag
      application: bidrag-statistikk
      access: readwrite
    - team: dv-familie
      application: dvh-familie-konsument
      access: read
    - team: bidrag
      application: bidrag-kafka-manager
      access: readwrite