apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: Vedtak Hendelser
    dcat.data.nav.no/description: Intern kø av hendelser på vedtak som oppstår i saksbehandlingen under team bidrag
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: vedtak-q2
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: bidrag
      application: bidrag-vedtak-q2
      access: readwrite
    - team: bidrag
      application: bidrag-behandling-q2
      access: read
    - team: bidrag
      application: bidrag-behandling
      access: read
    - team: bidrag
      application: bidrag-stonad-q2
      access: read
    - team: bidrag
      application: bidrag-regnskap-q2
      access: read
    - team: bidrag
      application: bidrag-automatisk-jobb-q2
      access: read
    - team: bidrag
      application: bidrag-kafka-manager
      access: read
    - team: bidrag
      application: bisys
      access: read
    - team: bidrag
      application: bidrag-cli
      access: readwrite
    - team: bidrag
      application: bidrag-statistikk-q2
      access: read
    - team: bidrag
      application: bidrag-stonad-temp-q2
      access: read
    - team: bidrag
      application: bidrag-belopshistorikk-q2
      access: read
