apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: Vedtak Hendelser
    dcat.data.nav.no/description: Intern kø av hendelser på vedtak som oppstår i saksbehandlingen under team bidrag
  name: vedtak-feature
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: bidrag
      application: bidrag-vedtak-feature
      access: readwrite
    - team: bidrag
      application: bidrag-stonad-feature
      access: read
    - team: bidrag
      application: bidrag-revurder-forskudd-data-feature
      access: read
    - team: bidrag
      application: bidrag-regnskap-feature
      access: read
    - team: bidrag
      application: bidrag-kafka-manager
      access: read