apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: Vedtaksforslag Hendelser
    dcat.data.nav.no/description: Intern kø av hendelser for vedtaksforslag som oppstår i saksbehandlingen under team bidrag
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: vedtaksforslag-q2
  namespace: bidrag
  labels:
    team: bidrag
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: bidrag
      application: bidrag-vedtak-q2
      access: readwrite
    - team: bidrag
      application: bidrag-behandling-q2
      access: read
    - team: bidrag
      application: bidrag-automatisk-jobb-q2
      access: read
    - team: bidrag
      application: bidrag-kafka-manager
      access: read
    - team: bidrag
      application: bisys
      access: read
    - team: bidrag
      application: bidrag-cli
      access: readwrite