name: setup kafka streams
on:
  push:
    branches:
      - '**'

env:
  TOPIC_FILES: bidrag/topics/journalpost.yaml,bidrag/topics/vedtak.yaml

jobs:

  setup-dev:
    runs-on: ubuntu-latest
    name: Set up kafka streams in dev
    if: github.ref != 'refs/heads/release'

    steps:
      - uses: actions/checkout@v2
        with:
          path: bidrag
      - name: use feature topic-files
        if: github.ref != 'refs/heads/main'
        run: echo TOPIC_FILES=bidrag/topics/journalpost-feature.yaml,bidrag/topics/vedtak-feature.yaml >> $GITHUB_ENV
      - name: Setup kafka in dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.TOPIC_FILES }}

  restarts:
    runs-on: self-hosted
    name: restart applications using kafka streams
    needs: setup-dev

    steps:
      - run: kubectl config use-context dev-fss
      - name: restart bidrag-dokument-journalpost-feature
        if: github.ref != 'refs/heads/main'
        run: |
          PODS=$(kubectl get pods -n bidrag -l app=bidrag-dokument-journalpost-feature  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS | sed 's;\n; ;')
      - name: restart bidrag-arbeidsflyt-feature
        if: github.ref != 'refs/heads/main'
        run: |
          PODS=$(kubectl get pods -n bidrag -l app=bidrag-arbeidsflyt-feature  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS | sed 's;\n; ;')
      - name: restart bidrag-dokument-journalpost
        if: github.ref == 'refs/heads/main'
        run: |
          PODS=$(kubectl get pods -n bidrag -l app=bidrag-dokument-journalpost  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS | sed 's;\n; ;')
      - name: restart bidrag-arbeidsflyt
        if: github.ref == 'refs/heads/main'
        run: |
          PODS=$(kubectl get pods -n bidrag -l app=bidrag-arbeidsflyt  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS | sed 's;\n; ;')

  setup-prod:
    runs-on: ubuntu-latest
    name: Set up kafka streams in prod
    if: github.ref == 'refs/heads/release'

    steps:
      - uses: actions/checkout@v2
        with:
          path: bidrag
      - name: Set up  to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: bidrag/topics/journalpost-prod.yaml,bidrag/topics/vedtak-prod.yaml
