name: setup kafka streams
on:
  push:
    branches:
      - '**'

env:
  TOPIC_FILES: bidrag/topics/journalpost.yaml,bidrag/topics/vedtak.yaml

jobs:

  setup-dev:
    runs-on: ubuntu-latest
    name: Set up kafka streams in dev
    if: github.ref != 'refs/heads/release'

    steps:
      - uses: actions/checkout@v2
        with:
          path: bidrag
      - name: use feature topic-files
        if: github.ref != 'refs/heads/main'
        run: echo TOPIC_FILES=bidrag/topics/journalpost-feature.yaml,bidrag/topics/vedtak-feature.yaml >> $GITHUB_ENV
      - name: Setup kafka in dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.TOPIC_FILES }}

  restarts:
    runs-on: self-hosted
    name: restart applications using kafka streams
    needs: setup-dev

    steps:
      - run: kubectl config use-context dev-fss
      - name: use applications in feature branch
        if: github.ref != 'refs/heads/main'
        run: echo NAIS_APPS="bidrag-dokument-journalpost-feature;bidrag-dokument-testdata-feature" >> $GITHUB_ENV
      - name: use applications in main branch
        if: github.ref == 'refs/heads/main'
        run: echo NAIS_APPS="bidrag-dokument-journalpost;bidrag-dokument-testdata" >> $GITHUB_ENV
      - name: restart applications
        run: |
          IFS=';' read -r -a APPS <<< "$NAIS_APPS"

          for app in APPS
          do
            APP_PODS=$(kubectl get pods -n bidrag -l app=$app | awk '{print $1}' | grep -v NAME)
            PODS=$(echo RESTART_PODS | sed 's;\n; ;')
            kubectl delete pods -n bidrag $PODS
            echo "Restarts $app, pods: $PODS"
          done

  setup-prod:
    runs-on: ubuntu-latest
    name: Set up kafka streams in prod
    if: github.ref == 'refs/heads/release'

    steps:
      - uses: actions/checkout@v2
        with:
          path: bidrag
      - name: Set up  to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: bidrag/topics/journalpost-prod.yaml,bidrag/topics/vedtak-prod.yaml
