name: setup kafka streams
on:
  push:
    branches:
      - '**'

env:
  TOPIC_FILES: bidrag/topics/journalpost.yaml,bidrag/topics/vedtak.yaml,bidrag/topics/dokument-dev.yaml,bidrag/topics/sak-dev.yaml,bidrag/topics/vedtak-syntetisk.yaml

jobs:

  setup-dev:
    runs-on: ubuntu-latest
    name: Set up kafka streams in dev

    steps:
      - uses: actions/checkout@v4
        with:
          path: bidrag
      - name: use feature topic-files
        if: github.ref != 'refs/heads/main'
        run: echo TOPIC_FILES=bidrag/topics/journalpost-feature.yaml,bidrag/topics/vedtak-feature.yaml,bidrag/topics/dokument-feature.yaml,bidrag/topics/sak-feature.yaml >> $GITHUB_ENV
      - name: Setup kafka in dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.TOPIC_FILES }}

  setup-prod:
    runs-on: ubuntu-latest
    name: Set up kafka streams in prod
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          path: bidrag
      - name: Set up to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: bidrag/topics/journalpost-prod.yaml,bidrag/topics/vedtak-prod.yaml,bidrag/topics/vedtak-prod.yaml,bidrag/topics/dokument-prod.yaml,bidrag/topics/sak-prod.yaml
