name: setup kafka streams
on:
  push:
    branches:
      - '**'

env:
  TOPIC_FILES: bidrag/topics/journalpost.yaml,bidrag/topics/journalpost-feature.yaml,bidrag/topics/dokument-dev.yaml,bidrag/topics/dokument-feature.yaml,bidrag/topics/sak-dev.yaml,bidrag/topics/sak-feature.yaml,bidrag/topics/vedtak-q1.yaml,bidrag/topics/vedtak-q2.yaml,bidrag/topics/vedtak-q4.yaml,bidrag/topics/samhandler-q1.yaml,bidrag/topics/samhandler-q2.yaml,bidrag/topics/samhandler-q4.yaml,bidrag/topics/statistikk-q2.yaml,bidrag/topics/vedtaksforslag-q1.yaml,bidrag/topics/vedtaksforslag-q2.yaml,bidrag/topics/vedtaksforslag-q4.yaml
permissions:
  contents: "read"
  id-token: "write"
jobs:
  setup-dev:
    runs-on: ubuntu-latest
    name: Set up kafka streams in dev

    steps:
      - uses: actions/checkout@v4
        with:
          path: bidrag
      - name: Setup kafka in dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.TOPIC_FILES }}

  setup-prod:
    runs-on: ubuntu-latest
    name: Set up kafka streams in prod
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          path: bidrag
      - name: Set up to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: bidrag/topics/journalpost-prod.yaml,bidrag/topics/vedtak-prod.yaml,bidrag/topics/dokument-prod.yaml,bidrag/topics/sak-prod.yaml,bidrag/topics/samhandler-prod.yaml,bidrag/topics/statistikk-prod.yaml,bidrag/topics/vedtaksforslag-prod.yaml
